### ISSUE TITLE
実行時エラーが起こる

### ISSUE THREAD

**Issue by saitenntaisei** [rogy-AquaLab/2023_robokit#42]
エラー内容は忘れました()
症状としてstm32 f303k8で書き込んだプログラムを実行しようとするとエラー表示がでる
シリアルモニターで詳細な内容を閲覧可能

**Comment by H1rono** [comment]
cc @suyu-hash

**Comment by H1rono** [comment]
```
start up


++ MbedOS Error Info ++
Error Status: 0x8001012F Code: 303 Module: 1
Error Message: Error - writing to a file in an ISR or critical section

Location: 0x8002839
Error Value: 0x1
Current Thread: main Id: 0x20001ABC Entry: 0x8001ADD StackSize: 0x1000 StackMem: 0x20000A98 SP: 0x20002EBC
For more info, visit: https://mbed.com/s/error?error=0x8001012F&tgt=NUCLEO_F303K8
-- MbedOS Error Info --
```

**Comment by H1rono** [comment]
#4 revertするのでいいかな...

**Comment by H1rono** [comment]
https://armmbed.github.io/mbedos-error/?error=0x8001012F&tgt=NUCLEO_F303K8

> ### ERROR CODE
> Operation Prohibited in ISR context
> Operation Prohibited in ISR context. For example, attempt to acquire a mutex object is not allowed in ISR context.

**Comment by H1rono** [comment]
https://github.com/rogy-AquaLab/2023_robokit/blob/72e8a0129b6db02fe42bfc7d3f464e5d54d20039/src/schneider_model.cpp#L37

多分ここ

**Comment by H1rono** [comment]
https://os.mbed.com/docs/mbed-os/v6.16/apis/ticker.html

**Comment by H1rono** [comment]
> ## Warnings and notes
> - No blocking code in ISR: avoid any call to wait, infinite while loop or blocking calls in general.
> - No printf, malloc or new in ISR: avoid any call to bulky library functions. In particular, certain library functions (such as printf, malloc and new) are not re-entrant, and their behavior could be corrupted when called from an ISR.
> - While an event is attached to a Ticker, deep sleep is blocked to maintain accurate timing. If you don't need microsecond precision, consider using the LowPowerTicker class instead because that does not block deep sleep mode.

https://github.com/rogy-AquaLab/2023_robokit/blob/72e8a0129b6db02fe42bfc7d3f464e5d54d20039/src/schneider_model.cpp#L109-L110

ここっぽいな

**Comment by H1rono** [comment]
@suyu-hash `NVIC_SystemReset`はどういう意図で書いてありますか？

**Comment by suyu-hash** [comment]
割り込み処理をシステムの停止って感じで使ってた気がします
NVIC_SystemReset がそれですね

**Comment by H1rono** [comment]
なるほど

**Comment by H1rono** [comment]
https://github.com/rogy-AquaLab/2023_robokit/blob/72e8a0129b6db02fe42bfc7d3f464e5d54d20039/src/schneider_model.cpp#L109-L110

ここだけコメントアウトしてもエラーが出た

https://github.com/rogy-AquaLab/2023_robokit/blob/72e8a0129b6db02fe42bfc7d3f464e5d54d20039/src/schneider_model.cpp#L37

ここを消したらエラーが消えたので、↓にエラーがありそう

https://github.com/rogy-AquaLab/2023_robokit/blob/72e8a0129b6db02fe42bfc7d3f464e5d54d20039/src/schneider_model.cpp#L224-L227

https://github.com/rogy-AquaLab/2023_robokit/blob/72e8a0129b6db02fe42bfc7d3f464e5d54d20039/src/schneider_model.cpp#L105-L111

**Comment by H1rono** [comment]
`printf`をコメントアウトしたら別のエラーが出た

```
start up


++ MbedOS Error Info ++
Error Status: 0x80FF0144 Code: 324 Module: 255
Error Message: Assertion failed: status == osOK
Location: 0x8001FBD
File: /home/pi/.platformio/packages/framework-mbed/rtos/source/ThisThread.cpp+225
Error Value: 0x0
Current Thread: main Id: 0x20001ABC Entry: 0x8001ADD StackSize: 0x1000 StackMem: 0x20000A98 SP: 0x20002F34 
For more info, visit: https://mbed.com/s/error?error=0x80FF0144&tgt=NUCLEO_F303K8
-- MbedOS Error Info --
```

**Comment by H1rono** [comment]
`rtos::ThisThread::sleep_for(5s);`もコメントアウトしたら数秒おきに`start up`が出るようになった
@suyu-hash 数秒おきにリセットがかかるのは意図した挙動ですか？

**Comment by H1rono** [comment]
約2秒おき... 😕

**Comment by suyu-hash** [comment]
> `rtos::ThisThread::sleep_for(5s);`もコメントアウトしたら数秒おきに`start up`が出るようになった @suyu-hash 数秒おきにリセットがかかるのは意図した挙動ですか？

いいえ。。。。

一旦、割り込み処理自体を無くしてもいいかもしれないですね

**Comment by H1rono** [comment]
最終手段ですね
もうちょい調べます

**Comment by H1rono** [comment]
これ、`D7`ピンがGNDに対して浮いてることが原因かもしれない

**Comment by H1rono** [comment]
3V3と繋げたらリセットかからなくなったので解決...?

**Comment by H1rono** [comment]
@suyu-hash ↑どうでしょうか？

**Comment by suyu-hash** [comment]
オンラインコンパイラでコンパイルしていたものは動いていたはずなので、ハード的な問題というよりはソフト側の問題だと思います(コンパイラとか)

https://github.com/rogy-AquaLab/2023_robokit/blob/72e8a0129b6db02fe42bfc7d3f464e5d54d20039/src/schneider_model.cpp#L109-L110
を `exit` とかにするとだめですかね？

**Comment by H1rono** [comment]
`exit`だと再起動がかからないですね
mbedOSのメジャーバージョンが上がってる(おそらく2→6になっている)ので挙動が異なるのは当然だと思います

https://github.com/rogy-AquaLab/2023_robokit/blob/72e8a0129b6db02fe42bfc7d3f464e5d54d20039/src/schneider_model.cpp#L225

割り込みの外で`button`の値を見たところ、D7がどこにもつながっていないと`0`になることが時々あったのでやっぱりハードの問題もあるのではないでしょうか？ @saitenntaisei どうなんでしょ

**Comment by saitenntaisei** [comment]
それ基板に刺されていないからじゃない?　D7がプルアップかプルダウンされているはず(回路図みてないけど)? 内部回路でプルアップとかプルダウンできた希ガス。　それか3回チェックして多数決とるとか?

**Comment by H1rono** [comment]
やりたいことは「故意にボタンが押された時のみリセットをかける」なので3回チェックは違う
回路図確認して、プルアップ・プルダウンになってたらこれで解決にしましょう

**Comment by H1rono** [comment]
![](https://i.imgur.com/5PNmPds.png)
D7(=PF0)浮いてね...?

**Comment by H1rono** [comment]
え、この割り込みいらない子ってこと？
